### ISSUE TITLE
SSH key authentication passphrase

### ISSUE THREAD

**Issue by AndreasMurk** [laur89/docker-borg-mysql-backup#12]
Hi!

I really like this script and want to use it in my k8s cluster with a deployment.

I have tried setting up the script and was able to successfully backup to a local repository, which I have mounted through a docker volume. However, what I am not able to get working yet is to backup a remote repository.

Borg uses ssh per default and I see that the public_key is added to the /root/.ssh/known_hosts file. This is working as intended. As soon as it comes to the point, where the backup will be created, it simply posts:

```
borg-backup  | Remote: user@remote: Permission denied (publickey,password).
borg-backup  | Connection closed by remote host. Is borg working on the server?
borg-backup  | terminating with error status, rc 2
```
I am aware that the problem might be because of authenticating the private key. I have set a passphrase for the ssh key, but cannot find the part where the key is being authenticated.

I tried to make a workaround, where I executed in the running docker container and added the key via `ssh-add /root/.ssh/id_rsa` and typed in the passphrase myself. Even if I am able to ssh into the other machine, the borg backup fails.

Am I missing here something?

Thanks in advance!

**Comment by laur89** [comment]
> I have set a passphrase for the ssh key, but cannot find the part where the key is being authenticated.

That'd be the issue - you're expected to use passwordless keys. 

> Even if I am able to ssh into the other machine, the borg backup fails.

Any errors? Sounds like maybe borg is not installed on the server?

**Comment by AndreasMurk** [comment]
Thanks for your fast answer!


> > I have set a passphrase for the ssh key, but cannot find the part where the key is being authenticated.
> 
> That'd be the issue - you're expected to use passwordless keys.
>> 
That was the missing piece. I now succesfully made the backup. Could you please write that down somewhere in the `README.md`? It was not clear for me to use passwordless keys. Thank you!
Would be there some solution in combination with an `ssh-agent` to use keys with passphrase? As it gets more secure in my opinion. If I have time, maybe I will do a PR and try to implement it 
> 
> > Even if I am able to ssh into the other machine, the borg backup fails.
> 
> Any errors? Sounds like maybe borg is not installed on the server?
>>
Borg is installed on the server. Everything works now!

Thank you for your help!

**Comment by laur89** [comment]
> Could you please write that down somewhere in the README.md

Will do.

> Would be there some solution in combination with an ssh-agent to use keys with passphrase? As it gets more secure in my opinion. If I have time, maybe I will do a PR and try to implement it

If you come up with a solution that's secure, I'd be willing to consider it for sure. But current implementation necessitates the key on the docker host is secured. All the simpler solutions (that I can think of anyway) with passwords would still expose it in a similar manner to the key, hence wouldn't really improve security (but _would_ make it more of a hassle to set up).

**Comment by laur89** [comment]
https://github.com/laur89/docker-borg-mysql-backup/commit/f560256087059b17a0a77accff114fcf111286b2

**Comment by laur89** [comment]
@andim202 if you're only now starting to use this service, I'd recommend taking a look at [borgmatic](https://torsion.org/borgmatic) first and see if it fits your use-case maybe better.

**Comment by AndreasMurk** [comment]
> @andim202 if you're only now starting to use this service, I'd recommend taking a look at [borgmatic](https://torsion.org/borgmatic) first and see if it fits your use-case maybe better.

Thank you so much! I just started with borg and everything, so this might be a better fit. I will let you know.

**Comment by laur89** [comment]
Borgmatic is much more featureful & allows for nicer, yaml-based configuration. Only downside I can think of is lack of docker orchestration support, but there is a [workaround](https://github.com/borgmatic-collective/docker-borgmatic/pull/88/files) avail.

Recommend taking a peek at the bottom of my project's readme, there are other cool alternatives out there. Been using my project for the past 5 years or so and can't be bothered to change the course now, it's fired & forgotten. But if I were to start from scratch today, I'd go with [duplicacy](https://github.com/gilbertchen/duplicacy) instead of borg - it allows lock-free uploads. Pure magic. Then again, with borg you find likely the cheapest cloud storage. So it all depends.

**Comment by AndreasMurk** [comment]
What exactly do you mean with docker orchestration support? That you cannot use it within an orchestration tool?

When building the image and using a deployment manifest, it could be deployed to k8s, I guess. I will have a look at that.

Thank you!

**Comment by laur89** [comment]
Nah I only meant the image doesn't include docker client, hence starting-stopping containers isn't as simple as `docker stop container`.
